name: CI workflow

env:
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  e2e:
    strategy:
      matrix:
        node-version:
          - 12.x
          - 14.x
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install PNPM
        run: npm install --global pnpm@6.x
      - run: pnpm install

      - run: pnpm run e2e
